sudo: true
dist: trusty

language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh  

script:
  - ./.travis/test.sh generate-count-matrix-py
  - ./.travis/unit-test.sh
